#version: '2'

services:
  hadoop:
    build: 
      context: .
      dockerfile: Dockerfile
    image: custom-hadoop
    container_name: hadoop
    user: root
    ports:
      - '8080:50070'
    volumes:
      - ./mounted-data:/data
    #command: /etc/bootstrap.sh -bash
      
